### ISSUE TITLE
open stream: ../smbios_entry_point: permission denied

### ISSUE THREAD

**Issue by masoudgs** [digitalocean/go-smbios#10]
I'm trying to use the sample code which placed in the README file but i got permission denied error.
```bash
2018/07/02 12:25:44 failed to open stream: open /sys/firmware/dmi/tables/smbios_entry_point: permission denied
```
How can i fix this?

**Comment by mdlayher** [comment]
Did you try running the program as root? As far as I can tell, accessing this data is a privileged operation. I'll leave this issue open to document it.

**Comment by mdlayher** [comment]
Noted in README: https://github.com/digitalocean/go-smbios/commit/6ea1edb18779bff9aed8a9e611f3b9904d470ad6.

**Comment by masoudgs** [comment]
Thanks, I'm not familiar with `CAP_DAC_OVERRIDE` and I had some search about that. How it'll possible to enable it?

**Comment by mdlayher** [comment]
Sure, check out https://wiki.archlinux.org/index.php/Capabilities for some additional reading.

**Comment by hghuyho** [comment]
I applied the CAP_DAC_OVERRIDE capability, but it did't work:

`setcap cap_dac_override+ep /sys/firmware/dmi/tables/smbios_entry_point`
`setcap cap_dac_override+ep /sys/firmware/dmi/tables/DMI`

The output log:
`%!(EXTRA *fs.PathError=open /sys/firmware/dmi/tables/smbios_entry_point: permission denied)
`
