### ISSUE TITLE
Add support for reading SMBIOS data on Windows

### ISSUE THREAD

**Issue by chris-dudley** [digitalocean/go-smbios#11]
I have already the code written to support this, but in accordance with the contributing guidelines I am opening an issue first.

I used the [GetSystemFirmwareTable](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724379(v=vs.85).aspx) function to retrieve the raw SMBIOS table data, which can then be passed to the Decoder.

Let me know if you would like me to open a pull request.

**Comment by mdlayher** [comment]
Very cool!  Please do open a PR!
