### ISSUE TITLE
how can i get string value in DSP0134, like this

### ISSUE THREAD

**Issue by xxxmailk** [digitalocean/go-smbios#13]
how can i get string value in DSP0134 like this, please.
04h    2.0+    Manufacturer     BYTE     STRING     Number of null-terminated string

**Comment by mdlayher** [comment]
Apologies, I haven't done too much with SMBIOS and am not entirely sure what you're asking for.

I suspect this is one of the structures in the stream (ID 134?). If you use this package to fetch the structures, you can probably decode the formatted area and/or strings from the structure with the ID you need by looking at the specification to see how the data is packed.

I'm mobile at the moment but I can try to look more into this in the next couple of days.

**Comment by mdlayher** [comment]
```
✔ ~/src/github.com/digitalocean/go-smbios/cmd/lssmbios [master|…1] 
13:55 $ sudo ./lssmbios | grep Gigabyte | head -n 1
&{{1 27 1} [1 2 3 4 116 2 212 3 53 4 231 5 203 6 196 7 0 8 0 9 6 5 6] [Gigabyte Technology Co., Ltd. Z97X-UD5H To be filled by O.E.M. To be filled by O.E.M. To be filled by O.E.M. To be filled by O.E.M.]}
```

The library takes care of gathering this particular information for you. Look at the strings section of the structure with type 1.

This isn't an bug or feature request, so I'd recommend closing this issue out if anyone from DigitalOcean sees this.

**Comment by xxxmailk** [comment]
Thanks for your answer
