### ISSUE TITLE
SMBIOS 3.4.0

### ISSUE THREAD

**Issue by andrewrynhard** [digitalocean/go-smbios#20]
I seem to have ran into a limitation in the current implementation. I believe the data I am after is in SMBIOS 3.4.0. Happy to help here, but curious if it is of interest to the maintainers?

**Comment by mdlayher** [comment]
Hey hey, I no longer have commit access to this repo but if you want to fork I'd be happy to provide insight there. What exactly are you after that is new in 3.4.0?

**Comment by andrewrynhard** [comment]
Hey @mdlayher. Looks like the Memory Device (type 17) has been expanded. Some useful bits in there for one of our projects.

**Comment by mdlayher** [comment]
AFAIK it should work as is because this library exposes the raw structures. There is no parsing for the individual structures in the upstream package.

**Comment by andrewrynhard** [comment]
Interesting. Ah, you know... I think I know why I am getting a panic. My host doesn't support 3.4 :facepalm: .

**Comment by mdlayher** [comment]
Yeah that'll do it. :)

**Comment by andrewrynhard** [comment]
Sorry for the noise.
