### ISSUE TITLE
Cannot assign 2 values to 3 variables

### ISSUE THREAD

**Issue by 0000day** [digitalocean/go-smbios#5]
Hi everyone.

I just downloaded the package and imported it into my project. `Go get` already showed up an error:

```
# github.com/digitalocean/go-smbios/smbios
..\github.com\digitalocean\go-smbios\smbios\decoder.go:50:14: cannot assign 2 values to 3 variables
```

It is `func Stream()` which is causing it. This is the source:

_github.com\digitalocean\go-smbios\smbios\decoder.go:49_
```
func Stream() (io.ReadCloser, EntryPoint, error) {
        // ERROR AT THIS LINE
	rc, ep, err := stream()
	if err != nil {
		return nil, nil, err
	}

	// The io.ReadCloser from stream could be any one of a number of types
	// depending on the source of the SMBIOS stream information.
	//
	// To prevent the caller from potentially tampering with something dangerous
	// like mmap'd memory by using a type assertion, we make the io.ReadCloser
	// into an opaque and unexported type to prevent type assertion.
	return &opaqueReadCloser{rc: rc}, ep, nil
}
```

As you can see the result of `stream()` gets assigned to 3 variables `rc`, `ep` and `err`. This is the declaration of `stream()`:

_github.com\digitalocean\go-smbios\smbios\stream_others.go:26_
```
func stream() (io.ReadCloser, error) {
	return nil, fmt.Errorf("opening SMBIOS stream not implemented on %q", runtime.GOOS)
}
```

Its returning `io.ReadCloser` and `error`.
Where should `EntryPoint` come from?

---------------------------------------------------------------
OS: Windows Pro
Arch: x64

**Comment by mdlayher** [comment]
Thanks for the information, it looks like I broke the build when I added the last pieces of code. In this case, the code doesn't support your current operating system. Which OS?

It's easy to get this working on most unix-like systems but a little less so on Mac and Windows.

**Comment by 0000day** [comment]
Oh sorry for the missing information. Its Windows Pro / x64. I for sure got alternative ways to go but I thought this issue would be interesting for you.

**Comment by mdlayher** [comment]
Yeah, so I'd like to support Windows but am not sure what the APIs are there. Will investigate more next week.

**Comment by mdlayher** [comment]
Fixed.
